services:
  - type: web
    name: taps-rezos
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn taps_rezos.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taps-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"

databases:
  - name: taps-db
    databaseName: taps
    user: taps_user