# Generated by Django 5.1.7 on 2025-03-18 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoviePoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start",
                    models.DateField(default=datetime.date(2025, 3, 18), unique=True),
                ),
                ("movie1", models.CharField(max_length=255)),
                ("movie2", models.CharField(max_length=255)),
                ("movie3", models.CharField(max_length=255)),
                ("movie1_votes", models.IntegerField(default=0)),
                ("movie2_votes", models.IntegerField(default=0)),
                ("movie3_votes", models.IntegerField(default=0)),
                (
                    "winning_movie",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("guests", models.IntegerField()),
                ("occasion", models.CharField(max_length=100)),
                ("seat_id", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
