# Generated by Django 5.1.7 on 2025-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rezo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="seat_id",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of seat IDs",
                max_length=255,
                null=True,
            ),
        ),
    ]
