# Generated by Django 5.1.6 on 2025-03-18 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rezo_app", "0002_alter_reservation_seat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviePoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="seat_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
