# Generated by Django 5.1.6 on 2025-03-28 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rezo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviepoll",
            name="week_start",
            field=models.DateField(default=datetime.date(2025, 3, 28), unique=True),
        ),
    ]
